### ISSUE TITLE
Issue with garage door status refreshing after triggering an open or close

### ISSUE THREAD

**Issue by rocker01** [ithinkdancan/hubitat-meross#1]
The status of the door won't refresh after triggering an open or a close from Hubitat.

Example: garage door is closed, I click open - the garage door opens but the "contact" and "door" field shows closed.

Perhaps it's this line of the code that is commented out?

Line 74:
// runIn(5000, refresh())

**Comment by BBuchel** [comment]
What I have realised is that the state will only change after the door is fully open or closed, and because it is a poll/refresh rather than push of status, I thought this may work in same location. Mine take about 25 seconds to fully open/close and Meross to report the status correctly. Also if you don’t have the overwrite as false, it would result in cancelling the normal scheduled refresh whereas this would add these to the scheduler…
        runIn(20, refresh, [overwrite: false])
        runIn(25, refresh, [overwrite: false])
        runIn(30, refresh, [overwrite: false])
        runIn(35, refresh, [overwrite: false])
Thoughts?
